include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - always_use_package_imports
    - lines_longer_than_80_chars
    - sort_constructors_first
    - prefer_expression_function_bodies # arrows :ohh_yeah:
    - unawaited_futures
